source/ShipbuildingRollingWeb/Controllers/CompanyDBController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShipbuildingRollingWeb.Models.DB;

namespace ShipbuildingRollingWeb.Controllers
{
    public class CompanyDBController : Controller
    {
        private ShipbuildingRollingDBEntities db = new ShipbuildingRollingDBEntities();

        // GET: CompanyDB
        public ActionResult Index()
        {
            ViewBag.Admin = User.IsInRole("admin");
            ViewBag.User = User.IsInRole("user");

            return View(db.CompanyDB.ToList());
        }

        // GET: CompanyDB/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyDB company = db.CompanyDB.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // GET: CompanyDB/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CompanyDB/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Address,Specialization")] CompanyDB company)
        {
            if (ModelState.IsValid)
            {
                company.ID = db.CompanyDB.ToList().Last().ID + 1;
                db.CompanyDB.Add(company);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(company);
        }

        // GET: CompanyDB/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyDB company = db.CompanyDB.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: CompanyDB/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Address,Specialization")] CompanyDB company)
        {
            if (ModelState.IsValid)
            {
                db.Entry(company).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(company);
        }

        // GET: CompanyDB/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyDB company = db.CompanyDB.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: CompanyDB/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CompanyDB company = db.CompanyDB.Find(id);
            db.CompanyDB.Remove(company);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

source/ShipbuildingRollingWeb/Controllers/DrawingDBController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShipbuildingRollingWeb.Models.DB;

namespace ShipbuildingRollingWeb.Controllers
{
    public class DrawingDBController : Controller
    {
        private ShipbuildingRollingDBEntities db = new ShipbuildingRollingDBEntities();

        // GET: DrawingDB
        public ActionResult Index()
        {
            ViewBag.Admin = User.IsInRole("admin");
            ViewBag.User = User.IsInRole("user");

            var drawingDB = db.DrawingDB.Include(d => d.BodyFragmentDB).Include(d => d.CompanyDB);
            return View(drawingDB.ToList());
        }

        // GET: DrawingDB/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DrawingDB drawing = db.DrawingDB.Find(id);
            if (drawing == null)
            {
                return HttpNotFound();
            }
            return View(drawing);
        }

        // GET: DrawingDB/Create
        public ActionResult Create()
        {
            ViewBag.BodyFragmentID = new SelectList(db.BodyFragmentDB, "ID", "Name");
            ViewBag.CompanyID = new SelectList(db.CompanyDB, "ID", "Name");
            return View();
        }

        // POST: DrawingDB/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BodyFragmentID,CompanyID,Data,Format")] DrawingDB drawing)
        {
            if (ModelState.IsValid)
            {
                drawing.ID = db.DrawingDB.ToList().Last().ID + 1;
                db.DrawingDB.Add(drawing);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BodyFragmentID = new SelectList(db.BodyFragmentDB, "ID", "Name", drawing.BodyFragmentID);
            ViewBag.CompanyID = new SelectList(db.CompanyDB, "ID", "Name", drawing.CompanyID);
            return View(drawing);
        }

        // GET: DrawingDB/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DrawingDB drawing = db.DrawingDB.Find(id);
            if (drawing == null)
            {
                return HttpNotFound();
            }
            ViewBag.BodyFragmentID = new SelectList(db.BodyFragmentDB, "ID", "Name", drawing.BodyFragmentID);
            ViewBag.CompanyID = new SelectList(db.CompanyDB, "ID", "Name", drawing.CompanyID);
            return View(drawing);
        }

        // POST: DrawingDB/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,BodyFragmentID,CompanyID,Data,Format")] DrawingDB drawingDB)
        {
            if (ModelState.IsValid)
            {
                db.Entry(drawingDB).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BodyFragmentID = new SelectList(db.BodyFragmentDB, "ID", "Name", drawingDB.BodyFragmentID);
            ViewBag.CompanyID = new SelectList(db.CompanyDB, "ID", "Name", drawingDB.CompanyID);
            return View(drawingDB);
        }

        // GET: DrawingDB/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DrawingDB drawing = db.DrawingDB.Find(id);
            if (drawing == null)
            {
                return HttpNotFound();
            }
            return View(drawing);
        }

        // POST: DrawingDB/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DrawingDB drawing = db.DrawingDB.Find(id);
            db.DrawingDB.Remove(drawing);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

source/ShipbuildingRollingWeb/Controllers/HomeController.cs
using System.Web.Mvc;

namespace ShipbuildingRollingWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Provider()
        {
            return View();
        }

        public ActionResult Producer()
        {
            return View();
        }

        public ActionResult BodyFragment()
        {
            return View();
        }

        public ActionResult Company()
        {
            return View();
        }

        public ActionResult Rollingr()
        {
            return View();
        }
    }
}

source/ShipbuildingRollingWeb/Controllers/ProducerDBController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShipbuildingRollingWeb.Models.DB;

namespace ShipbuildingRollingWeb.Controllers
{
    public class ProducerDBController : Controller
    {
        private ShipbuildingRollingDBEntities db = new ShipbuildingRollingDBEntities();

        // GET: ProducerDB
        public ActionResult Index()
        {
            ViewBag.Admin = User.IsInRole("admin");
            ViewBag.User = User.IsInRole("user");

            return View(db.ProducerDB.ToList());
        }

        // GET: ProducerDB/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProducerDB producer = db.ProducerDB.Find(id);
            if (producer == null)
            {
                return HttpNotFound();
            }
            return View(producer);
        }

        // GET: ProducerDB/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProducerDB/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Address")] ProducerDB producer)
        {
            if (ModelState.IsValid)
            {
                producer.ID = db.ProducerDB.ToList().Last().ID + 1;
                db.ProducerDB.Add(producer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(producer);
        }

        // GET: ProducerDB/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProducerDB producer = db.ProducerDB.Find(id);
            if (producer == null)
            {
                return HttpNotFound();
            }
            return View(producer);
        }

        // POST: ProducerDB/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Address")] ProducerDB producer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(producer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(producer);
        }

        // GET: ProducerDB/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProducerDB producer = db.ProducerDB.Find(id);
            if (producer == null)
            {
                return HttpNotFound();
            }
            return View(producer);
        }

        // POST: ProducerDB/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProducerDB producer = db.ProducerDB.Find(id);
            db.ProducerDB.Remove(producer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

source/ShipbuildingRollingWeb/Controllers/RollingDBController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShipbuildingRollingWeb.Models.DB;

namespace ShipbuildingRollingWeb.Controllers
{
    public class RollingDBController : Controller
    {
        private ShipbuildingRollingDBEntities db = new ShipbuildingRollingDBEntities();

        // GET: RollingDB
        public ActionResult Index()
        {
            ViewBag.Admin = User.IsInRole("admin");
            ViewBag.User = User.IsInRole("user");

            var rollingDB = db.RollingDB.Include(r => r.ProducerDB).Include(r => r.ProvidersDB);
            return View(rollingDB.ToList());
        }

        // GET: RollingDB/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RollingDB rolling = db.RollingDB.Find(id);
            if (rolling == null)
            {
                return HttpNotFound();
            }
            return View(rolling);
        }

        // GET: RollingDB/Create
        public ActionResult Create()
        {
            ViewBag.ProducerID = new SelectList(db.ProducerDB, "ID", "Name");
            ViewBag.ProviderID = new SelectList(db.ProvidersDB, "ID", "Name");
            return View();
        }

        // POST: RollingDB/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProviderID,ProducerID,Name,Document,Form,Processing")] RollingDB rolling)
        {
            if (ModelState.IsValid)
            {
                rolling.ID = db.RollingDB.ToList().Last().ID + 1;
                db.RollingDB.Add(rolling);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProducerID = new SelectList(db.ProducerDB, "ID", "Name", rolling.ProducerID);
            ViewBag.ProviderID = new SelectList(db.ProvidersDB, "ID", "Name", rolling.ProviderID);
            return View(rolling);
        }

        // GET: RollingDB/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RollingDB rolling = db.RollingDB.Find(id);
            if (rolling == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProducerID = new SelectList(db.ProducerDB, "ID", "Name", rolling.ProducerID);
            ViewBag.ProviderID = new SelectList(db.ProvidersDB, "ID", "Name", rolling.ProviderID);
            return View(rolling);
        }

        // POST: RollingDB/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ProviderID,ProducerID,Name,Document,Form,Processing")] RollingDB rollingDB)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rollingDB).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProducerID = new SelectList(db.ProducerDB, "ID", "Name", rollingDB.ProducerID);
            ViewBag.ProviderID = new SelectList(db.ProvidersDB, "ID", "Name", rollingDB.ProviderID);
            return View(rollingDB);
        }

        // GET: RollingDB/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RollingDB rolling = db.RollingDB.Find(id);
            if (rolling == null)
            {
                return HttpNotFound();
            }
            return View(rolling);
        }

        // POST: RollingDB/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RollingDB rolling = db.RollingDB.Find(id);
            db.RollingDB.Remove(rolling);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

source/ShipbuildingRollingWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@section styles{
    @Styles.Render("~/Content/index.css");
}

@section Body{
    <div class="jumbotron">
    </div>

    <div class="container main">
        <div class="row text-center">
            <br><br>
            <div class="col-sm-4">
                <i class="fa fa-ship"></i>
                <h4>
                    @Html.ActionLink("Фрагменты корпуса", "Index", "BodyFragmentDB")
                </h4>
                <p>
                    Фрагменты корпуса, их краткие обозначения и название проката, из которого они сделаны
                </p>
            </div>
            <div class="col-sm-4">
                <i class="fa fa-anchor"></i>
                <h4>
                    @Html.ActionLink("Судостроительные предприятия", "Index", "CompanyDB")
                </h4>
                <p>
                    Названия судостроительных предприятий, их юридические адреса и основная специализация
                </p>
            </div>
            <div class="col-sm-4">
                <i class="fa fa-pencil"></i>
                <h4>
                    @Html.ActionLink("Чертежи", "Index", "DrawingDB")
                </h4>
                <p>
                    Каждый чертеж разработан для конкретного фрагмента корпуса, одним из судостроительных предприятий 
                    и имеет дату своего создания, а также формат
                </p>
            </div>
        </div>
        <div class="row text-center row-space">
            <br /><br />
            <div class="col-sm-4">
                <i class="fa fa-truck"></i>
                <h4>
                    @Html.ActionLink("Поставщики", "Index", "ProvidersDB")
                </h4>
                <p>
                    Названия компаний, поставляющих судостроительный прокат от производителей проката к
                    судостроительным предприятиям
                </p>
            </div>
            <div class="col-sm-4">
                <i class="fa fa-industry"></i>
                <h4>
                    @Html.ActionLink("Производители", "Index", "ProducerDB")
                </h4>
                <p>
                    Названия компаний, производящих судостроительный прокат и их юридические адреса
                </p>
            </div>
            <div class="col-sm-4">
                <i class="fa fa-square"></i>
                <h4>
                    @Html.ActionLink("Прокат", "Index", "RollingDB")
                </h4>
                <p>
                    Каждое наименование проката содержит информацию о производителе,
                    поставщике, документе на данный прокат, форме и виду обработке
                </p>
            </div>
        </div>
    </div>
}

source/ShipbuildingRollingWeb/Views/Home/Provider.cshtml
@{
    ViewBag.Title = "Provider";
}

@section styles{
    @Styles.Render("~/Content/index.css");
}

@section Body{
    <div class="container" style="margin-top: 200px">
        <div class="row text-justify">
            <div class="col-sm-4">
                <img src="~/Content/Providers/rdm.jpg" class="img-responsive center-block" />
                <h4>Региональный Дом Металла</h4>
                <p>
                    Компания "Региональный дом металла" - активный участник металлургической отрасли
                    Северо-Западного региона по оказанию услуг подбора, сборки, продажи и доставке металлопроката и изделий из стали.
                </p>
            </div>

            <div class="col-sm-4">
                <img src="~/Content/Providers/c235.png" class="img-responsive center-block" />
                <h4>С235</h4>
                <p>
                    Компания С235 групп основана в 2009 году в городе Москве и является одним из крупнейших поставщиков металлопроката и стальных труб в России. 
                    Предлагает профильные трубы со складов в Москве и Московской области. Поставляет широкий ассортимент профильных труб в различном исполнении - 
                    строительные профили, общего назначения, тонкостенные и мебельные трубы.
                </p>
            </div>

            <div class="col-sm-4">
                <img src="~/Content/Providers/lador.png" class="img-responsive center-block" />
                <h4>Ладор</h4>
                <p>
                    Появление имени "Ладор Комплект" в реестре металлоторговцев датировано 2004 годом. 
                    Целью создания фирмы являлось обеспечение сбыта трубной продукции в московском регионе. 
                    Начав с нескольких сотен тонн, объем месячных продаж впоследствии был доведен до 2,5 тыс. тонн.
                </p>
            </div>
        </div>

        <div class="row text-justify row-space">
            <div class="col-sm-6 col-align-bottom">
                <img src="~/Content/Providers/orion.png" class="img-responsive center-block" style="width:40%" />
                <h4>Орион-Металл</h4>
                <p>
                    Компания «Орион-Металл» в течение 13 лет осуществляет поставки металлопроката, профнастила и кровельных систем и
                    на сегодняшний день занимает лидирующие позиции в регионах своего присутствия.
                    Основной вид деятельности - продажа металлопроката и металлоизделий собственного производства.
                </p>
            </div>

            <div class="col-sm-6 col-align-bottom">
                <img src="~/Content/Providers/aprom.jpg" class="img-responsive center-block" style="width: 40%" />
                <h4>Апром Групп</h4>
                <p>
                    ООО "Апром Групп" работает в сфере продаж черного и нержавеющего металлопроката с 2014 года. 
                    Осуществляет оптовые и розничные поставки во все регионы РФ, а также страны СНГ.
                </p>
            </div>
        </div>
    </div>

}